name: CI

on:
  push:
分支:
      - main

  pull_request:
分支:
      - main
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [lts/*]
      fail-fast: false

    if: github.repository == 'byodian/oneimg'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 🔎 Check code lint
        run: pnpm lint

      - name: 🔎 Type check
        run: pnpm typecheck

      - name: 🚀 Build the project
        run: pnpm build

      - name: ✅ Verify build output
        shell: bash
        run: |
          if [ ! -d "./.next" ]; then
            echo "Build failed: .next directory not found."
            exit 1
          else
            echo "Build succeeded! 🎉"
          fi
